#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyroSens,       sensorGyro)
#pragma config(Sensor, dgtl2,  pistonTwo,      sensorDigitalOut)
#pragma config(Sensor, dgtl3,  pistonOne,      sensorDigitalOut)
#pragma config(Sensor, dgtl10, TEST_BUMP,      sensorTouch)
#pragma config(Sensor, I2C_1,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  mobileEncoder,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  liftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           liftRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port3,           mobileCapture, tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port6,           backLeft,      tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port7,           frontRight,    tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port8,           frictionDrum2, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftLeft,      tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "motion.h"
//#include "motionPlus.h"
#include "sensors.h"
#include "autonBlue.h"

// waits until a LCD button is pressed
void stall();
// stalls, then waits 'secs' seconds
void countdown(int secs);
// displays 's' to the LCD on line 'line', then stalls
void info(int line, const string s);

task main() {
	displayBatteryLevels();

	stall();
	clearLCDLine(0);
	displayLCDCenteredString(0, "Test Blue Auton");

	setPistons(PISTON_RETRACT);
	countdown(3);
	resetSensors();
	autonBlue();
}

//================================================
//================= DEFINITIONS ==================
//================================================

void stall() {
	while ((int)nLCDButtons == 0) {
		/* wait for button to be pressed */
		wait1Msec(50);
	}
	while ((int)nLCDButtons != 0) {
		/* wait for button to be released */;
		wait1Msec(50);
	}
}

void info(int line, const string s) {
	clearLCDLine(line);
	displayLCDString(line, 0, s);
	stall();
}

void countdown(int secs) {
	clearLCDLine(0);
	info(0, "countdown...");
	for (int i = secs; i > 0; --i) {
		clearLCDLine(0);
		displayLCDNumber(0, 0, i);
		wait1Msec(1000);
	}
}
